/**
 * Shared test helpers for the renderer suite: structural assertions plus a
 * tiny dependency-free XML well-formedness check (tag-balance tokenizer).
 *
 * The check is deliberately small, not a parser: renderer output is machine-
 * generated by SvgBuilder with all text/attribute content XML-escaped, so
 * '>' never appears inside an attribute value and the grammar reduces to
 * prolog/comments, open/close/self-closing tags, and text runs.
 */

import assert from 'node:assert/strict';
import test from 'node:test';
import { loadDiagramArchetype } from '../lib/diagram.js';
import type { Renderer } from '../types.js';

/**
 * Throws AssertionError unless `doc` is a balanced XML document with exactly
 * one root element. (~30 lines; no new deps.)
 */
export function assertWellFormedXml(doc: string): void {
  const tokens = doc.match(/<\?[\s\S]*?\?>|<!--[\s\S]*?-->|<!DOCTYPE[^>]*>|<\/?[A-Za-z][^>]*>|[^<]+/g);
  assert.ok(tokens !== null, 'document must contain at least one token');
  const stack: string[] = [];
  let roots = 0;
  for (const token of tokens) {
    if (token.startsWith('<?') || token.startsWith('<!--') || token.startsWith('<!DOCTYPE')) {
      assert.strictEqual(stack.length, 0, `${token.slice(0, 20)}… outside the root element`);
      continue;
    }
    if (!token.startsWith('<')) continue; // text run
    const close = token.match(/^<\/([A-Za-z][\w:.-]*)\s*>$/);
    if (close !== null) {
      assert.ok(stack.length > 0, `closing </${close[1]}> with empty stack`);
      assert.strictEqual(stack.pop(), close[1], `mismatched closing tag </${close[1]}>`);
      continue;
    }
    const open = token.match(/^<([A-Za-z][\w:.-]*)([\s\S]*)>$/);
    assert.ok(open !== null, `malformed tag: ${token.slice(0, 40)}`);
    const selfClosing = open[2]!.trimEnd().endsWith('/');
    if (!selfClosing) {
      stack.push(open[1]!);
      if (stack.length === 1) roots += 1;
    } else if (stack.length === 0) {
      roots += 1;
    }
    assert.ok(roots <= 1, 'more than one root element');
  }
  assert.deepStrictEqual(stack, [], `unclosed elements: ${stack.join(', ')}`);
  assert.strictEqual(roots, 1, 'exactly one root element required');
}

/** Structural guarantees every renderer output must satisfy. */
export function assertSvgStructure(svg: string): void {
  assert.ok(svg.startsWith('<?xml') || svg.startsWith('<svg'), 'must start with the XML prolog or <svg');
  assert.ok(svg.endsWith('</svg>\n'), 'must end with </svg> + newline');
  assert.ok(svg.includes('viewBox'), 'must declare a viewBox');
  assert.ok(svg.includes('role="img"'), 'must carry role="img"');
  assert.ok(svg.includes('<title>'), 'must include a <title>');
  const svgOpenTags = svg.match(/<svg[\s>]/g) ?? [];
  assert.strictEqual(svgOpenTags.length, 1, 'exactly one root <svg> element');
  assertWellFormedXml(svg);
}

/** One param-coverage case: `params` must render differently from golden. */
export interface CoverageCase {
  /** The top-level paramsSchema key being exercised. */
  key: string;
  params: Record<string, unknown>;
}

/** One invalid-params case: render must throw with `match` in the message. */
export interface InvalidCase {
  label: string;
  params: Record<string, unknown>;
  /** Substring or regex expected in the error message (the jsonPath locator). */
  match: string | RegExp;
}

/** Renders and returns the golden SVG for a renderer. */
export function renderGolden(
  render: (params: Record<string, unknown>) => string,
  golden: Record<string, unknown>,
): string {
  return render(structuredClone(golden));
}

// ---------------------------------------------------------------------------
// Shared per-renderer suite
// ---------------------------------------------------------------------------

export interface RendererSuiteSpec {
  archetypeId: string;
  golden: Record<string, unknown>;
  /**
   * One case per top-level paramsSchema property; each must change the
   * rendered output relative to golden.
   */
  coverage: CoverageCase[];
  invalid: InvalidCase[];
}

/**
 * Runs the standard renderer contract suite against a single renderer:
 * determinism, document structure, XML well-formedness, param coverage
 * (every top-level schema key affects output), and invalid-params rejection
 * (errors carry a jsonPath locator).
 */
export function runRendererSuite(
  renderer: Renderer,
  spec: RendererSuiteSpec,
): void {
  assert.strictEqual(renderer.archetypeId, spec.archetypeId, 'suite/renderer archetype mismatch');

  void test('determinism: identical params render byte-identical SVG', () => {
    const a = renderer.render(structuredClone(spec.golden));
    const b = renderer.render(structuredClone(spec.golden));
    assert.strictEqual(a, b);
  });

  void test('structure: prolog, single root <svg>, viewBox, role, title, trailing newline', () => {
    assertSvgStructure(renderer.render(structuredClone(spec.golden)));
  });

  void test('well-formed XML: balanced tags, one root element', () => {
    assertWellFormedXml(renderer.render(structuredClone(spec.golden)));
  });

  void test('param coverage: every top-level paramsSchema key affects output', () => {
    const goldenSvg = renderer.render(structuredClone(spec.golden));
    const covered = new Set(spec.coverage.map((c) => c.key));
    const { paramsSchema } = loadDiagramArchetype(spec.archetypeId);
    const schemaKeys = Object.keys(
      (paramsSchema as { properties?: Record<string, unknown> }).properties ?? {},
    );
    for (const key of schemaKeys) {
      assert.ok(covered.has(key), `paramsSchema key '${key}' has no coverage case`);
    }
    for (const c of spec.coverage) {
      const variantSvg = renderer.render(structuredClone(c.params));
      assert.notStrictEqual(
        variantSvg,
        goldenSvg,
        `varying key '${c.key}' did not change the output`,
      );
      assertWellFormedXml(variantSvg);
    }
  });

  void test('invalid params: rejected with a jsonPath locator in the message', () => {
    for (const c of spec.invalid) {
      assert.throws(
        () => renderer.render(structuredClone(c.params)),
        (err: unknown) => {
          assert.ok(err instanceof Error, 'thrown value must be an Error');
          if (typeof c.match === 'string') {
            assert.ok(
              err.message.includes(c.match),
              `error for '${c.label}' must mention '${c.match}', got: ${err.message}`,
            );
          } else {
            assert.match(err.message, c.match);
          }
          return true;
        },
        `case '${c.label}' must throw`,
      );
    }
  });
}
